version: "27.3.1"
services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/oms-db
  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"
  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
  notification-service:
    build: ./notification-service
    ports:
      - "8085:8085"
  product-service:
    build: ./product-service
    ports:
      - "8086:8086"
  frontend:
    build:
      context: ./oms-app
    environment:
      - VITE_API_BASE_URL=http://gateway-service:8080
    ports:
      - "3000:3000"
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: oms-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: congduc003
    ports:
      - "5432:5432"

